/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorResponse;
import io.swagger.model.Teacher;
import io.swagger.model.TeachersList;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-30T23:06:14.797-07:00")

@Api(value = "teachers", description = "the teachers API")
public interface TeachersApi {

    @ApiOperation(value = "Delete teacher by Id", nickname = "deleteTeacherById", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Success"),
        @ApiResponse(code = 400, message = "Bad request - some of the input parameters are incorrect or invalid", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "Resource Not Found", response = ErrorResponse.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = ErrorResponse.class) })
    @RequestMapping(value = "/teachers/{teacherId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTeacherById(@ApiParam(value = "Unique identifier of the devotee's account" ,required=true) @RequestHeader(value="User-Name", required=true) String userName,@ApiParam(value = "Id of the teacher to be deleted",required=true) @PathVariable("teacherId") String teacherId);


    @ApiOperation(value = "Retrieves teacher by Id", nickname = "getTeacherById", notes = "", response = Teacher.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Teacher.class),
        @ApiResponse(code = 400, message = "Bad request - some of the input parameters are incorrect or invalid", response = ErrorResponse.class),
        @ApiResponse(code = 403, message = "Forbidden - the devotee does not have permissions to call this endpoint", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "Resource Not Found", response = ErrorResponse.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = ErrorResponse.class) })
    @RequestMapping(value = "/teachers/{teacherId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Teacher> getTeacherById(@ApiParam(value = "Unique identifier of the devotee's account" ,required=true) @RequestHeader(value="User-Name", required=true) String userName,@ApiParam(value = "Id of the teacher to be retrieved",required=true) @PathVariable("teacherId") String teacherId);


    @ApiOperation(value = "Retrieves list of teachers", nickname = "getTeachers", notes = "", response = TeachersList.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = TeachersList.class),
        @ApiResponse(code = 400, message = "Bad request - some of the input parameters are incorrect or invalid", response = ErrorResponse.class),
        @ApiResponse(code = 403, message = "Forbidden - the devotee does not have permissions to call this endpoint", response = ErrorResponse.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = ErrorResponse.class) })
    @RequestMapping(value = "/teachers",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<TeachersList> getTeachers(@ApiParam(value = "Unique identifier of the devotee's account" ,required=true) @RequestHeader(value="User-Name", required=true) String userName);


    @ApiOperation(value = "Adds a new teacher", nickname = "onboardTeacher", notes = "", response = Teacher.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Teacher.class),
        @ApiResponse(code = 400, message = "Bad request - some of the input parameters are incorrect or invalid", response = ErrorResponse.class),
        @ApiResponse(code = 403, message = "Forbidden - the devotee does not have permissions to call this endpoint", response = ErrorResponse.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = ErrorResponse.class) })
    @RequestMapping(value = "/teachers",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Teacher> onboardTeacher(@ApiParam(value = "Unique identifier of the devotee's account" ,required=true) @RequestHeader(value="User-Name", required=true) String userName,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Teacher body);


    @ApiOperation(value = "Updates a teacher", nickname = "updateTeacher", notes = "Body of the PATCH request must conform to JSON Merge Patch specification outlined in RFC7396", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Success"),
        @ApiResponse(code = 400, message = "Bad request - some of the input parameters are incorrect or invalid", response = ErrorResponse.class),
        @ApiResponse(code = 403, message = "Forbidden - the devotee does not have permissions to call this endpoint", response = ErrorResponse.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = ErrorResponse.class) })
    @RequestMapping(value = "/teachers/{teacherId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    ResponseEntity<Void> updateTeacher(@ApiParam(value = "Unique identifier of the devotee's account" ,required=true) @RequestHeader(value="User-Name", required=true) String userName,@ApiParam(value = "Id of the teacher to be updated",required=true) @PathVariable("teacherId") String teacherId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Teacher body);

}
